command_timeout = 1000

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)[❯](bold yellow)"
error_symbol = "[❯](bold purple)[❯](bold red)"
