[tools]
lazygit = "latest"
go = "latest"
node = "lts"
pnpm = "latest"
java = "latest"
maven = "latest"
herdr = "latest"
"github:earendil-works/pi" = "latest"
opencode = "latest"
claude = "latest"
gemini = "latest"
agy = "latest"
"aqua:rtk-ai/rtk" = "latest"
usage = "3.3.0"
kubecolor = "0.6.0"

[settings]
minimum_release_age = "0s"
