export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
	git
	zsh-autosuggestions
	golang
	docker
	kubectl
	kube-ps1
	helm
	gcloud
	mvn
	gradle
	npm
	yarn
	bazel
	fzf
)

source $ZSH/oh-my-zsh.sh

## Mappings
# iterm
bindkey "\e\e[D" backward-word # ⌥←
bindkey "\e\e[C" forward-word # ⌥→
# kitty
bindkey "\e[1;3D" backward-word # ⌥←
bindkey "\e[1;3C" forward-word # ⌥→

# prompt
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure

# kube-ps1 prompt
function get_cluster_short() {
	echo "$1" | cut -d _ -f4 | cut -d - -f3
}

KUBE_PS1_CLUSTER_FUNCTION=get_cluster_short
KUBE_PS1_SYMBOL_ENABLE=false
KUBE_PS1_NS_ENABLE=false
unset KUBE_PS1_PREFIX
KUBE_PS1_SUFFIX=" "

PROMPT='$(kube_ps1)'$PROMPT

## Profile configs ##
[ -f "$HOME/.shell/profile" ] && source $HOME/.shell/profile

# Google Cloud SDK.
if [ -f "$HOME/.google-cloud-sdk/path.zsh.inc" ]; then source "$HOME/.google-cloud-sdk/path.zsh.inc"; fi
# The next line enables shell command completion for gcloud.
if [ -f "$HOME/.google-cloud-sdk/completion.zsh.inc" ]; then source "$HOME/.google-cloud-sdk/completion.zsh.inc"; fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -s ~/.luaver/luaver ] && . ~/.luaver/luaver

